# Project 2: Cancer Rates vs. Pharmaceutical Sales Across Countries

This project investigates whether a relationship exists between cancer rates and pharmaceutical sales across countries using data from the OECD. The analysis focuses on Belgium and Australia in 2014, the two countries with the most complete data for both metrics. An interactive grouped bar chart built with Plotly Express compares the two variables side by side. The results show that while Belgium and Australia have similar cancer rates, their pharmaceutical sales differ significantly, suggesting there is not enough evidence to conclude a correlation between cancer rates and pharmaceutical spending.

In [ ]:
# Project 2: Cancer Rates vs. Pharmaceutical Sales Across Countries

import plotly.io as pio

pio.renderers.default = "vscode+jupyterlab+notebook_connected"
import pandas as pd
import plotly.express as px

In [8]:
cancercare = pd.read_csv("OECD.ELS.HD,DSD_HCQO@DF_CC,1.0+.A.....OBS.csv")
cancercare

     STRUCTURE                     STRUCTURE_ID STRUCTURE_NAME ACTION  \0     DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   1     DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   2     DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   3     DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   4     DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   ...        ...                              ...            ...    ...   2145  DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   2146  DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   2147  DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   2148  DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I   2149  DATAFLOW  OECD.ELS.HD:DSD_HCQO@DF_CC(1.0)    Cancer care      I        REF_AREA   Reference area FREQ Frequency of observation   MEASURE  \0         CAN           Canada    A                   Annual  CCCLNTSR   1         CAN           Canada    A                   Annual  CCCLNTSR   2         TUR          TÃ¼rkiye    A                   Annual  CCCLNTSR   3         TUR          TÃ¼rkiye    A                   Annual  CCCLNTSR   4         ISR           Israel    A                   Annual  CCCLNTSR   ...       ...              ...  ...                      ...       ...   2145      DEU          Germany    A                   Annual  CCLUNTSR   2146      SVK  Slovak Republic    A                   Annual  CCLKNTSR   2147      ISL          Iceland    A                   Annual  CCCLNTSR   2148      USA    United States    A                   Annual  CCRTNTSR   2149      AUT          Austria    A                   Annual  CCCLNTSR                                                   Measure  ... DECIMALS  \0                   Colon cancer five-year net survival  ...        1   1                   Colon cancer five-year net survival  ...        1   2                   Colon cancer five-year net survival  ...        1   3                   Colon cancer five-year net survival  ...        1   4                   Colon cancer five-year net survival  ...        1   ...                                                 ...  ...      ...   2145                 Lung cancer five-year net survival  ...        1   2146  Childhood acute lymphoblastic leukaemia five-y...  ...        1   2147                Colon cancer five-year net survival  ...        1   2148               Rectal cancer five-year net survival  ...        1   2149                Colon cancer five-year net survival  ...        1        Decimals OBS_STATUS Observation status OBS_STATUS2 Observation status 2  \0         One        NaN                NaN         NaN                  NaN   1         One        NaN                NaN         NaN                  NaN   2         One        NaN                NaN         NaN                  NaN   3         One        NaN                NaN         NaN                  NaN   4         One        NaN                NaN         NaN                  NaN   ...       ...        ...                ...         ...                  ...   2145      One        NaN                NaN         NaN                  NaN   2146      One        NaN                NaN         NaN                  NaN   2147      One        NaN                NaN         NaN                  NaN   2148      One        NaN                NaN         NaN                  NaN   2149      One        NaN                NaN         NaN                  NaN        OBS_STATUS3 Observation status 3  UNIT_MULT  Unit multiplier  0            NaN                  NaN          0            Units  1            NaN                  NaN          0            Units  2            NaN                  NaN          0            Units  3            NaN                  NaN          0            Units  4            NaN                  NaN          0            Units  ...          ...                  ...        ...              ...  2145         NaN                  NaN          0            Units  2146         NaN                  NaN          0            Units  2147         NaN                  NaN          0            Units  2148         NaN                  NaN          0            Units  2149         NaN                  NaN          0            Units  [2150 rows x 38 columns]

Download the data

URL: https://data-explorer.oecd.org/vis?df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_HCQO%40DF_CC&df[ag]=OECD.ELS.HD&df[vs]=1.0&dq=.A.....OBS&pd=2004%2C&to[TIME_PERIOD]=false

In [9]:
cancercare.info()

<class 'pandas.core.frame.DataFrame'>RangeIndex: 2150 entries, 0 to 2149Data columns (total 38 columns): #   Column                    Non-Null Count  Dtype  ---  ------                    --------------  -----   0   STRUCTURE                 2150 non-null   object  1   STRUCTURE_ID              2150 non-null   object  2   STRUCTURE_NAME            2150 non-null   object  3   ACTION                    2150 non-null   object  4   REF_AREA                  2150 non-null   object  5   Reference area            2150 non-null   object  6   FREQ                      2150 non-null   object  7   Frequency of observation  2150 non-null   object  8   MEASURE                   2150 non-null   object  9   Measure                   2150 non-null   object  10  UNIT_MEASURE              2150 non-null   object  11  Unit of measure           2150 non-null   object  12  AGE                       2150 non-null   object  13  Age                       2150 non-null   object  14  SEX                       2150 non-null   object  15  Sex                       2150 non-null   object  16  STATISTICAL_OPERATION     2150 non-null   object  17  Statistical operation     2150 non-null   object  18  TIME_PERIOD               2150 non-null   int64   19  Time period               0 non-null      float64 20  OBS_VALUE                 2150 non-null   float64 21  Observation value         0 non-null      float64 22  HSPA                      0 non-null      float64 23  HSPA.1                    0 non-null      float64 24  METHODOLOGY               2150 non-null   object  25  Calculation methodology   2150 non-null   object  26  TIME_RANGE                2150 non-null   object  27  Time range                0 non-null      float64 28  DECIMALS                  2150 non-null   int64   29  Decimals                  2150 non-null   object  30  OBS_STATUS                19 non-null     object  31  Observation status        19 non-null     object  32  OBS_STATUS2               0 non-null      float64 33  Observation status 2      0 non-null      float64 34  OBS_STATUS3               0 non-null      float64 35  Observation status 3      0 non-null      float64 36  UNIT_MULT                 2150 non-null   int64   37  Unit multiplier           2150 non-null   object dtypes: float64(10), int64(3), object(25)memory usage: 638.4+ KB

Looking to see which columns are recorded as strings or floats

In [10]:
pharmsales = pd.read_csv("OECD.ELS.HD,HEALTH_PHMC@DF_PHMC_SALES,+..USD_PPP_PS.._T.csv")
pharmsales

    STRUCTURE                                STRUCTURE_ID  \0    DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   1    DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   2    DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   3    DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   4    DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   ..        ...                                         ...   387  DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   388  DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   389  DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   390  DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)   391  DATAFLOW  OECD.ELS.HD:HEALTH_PHMC@DF_PHMC_SALES(1.0)               STRUCTURE_NAME ACTION REF_AREA Reference area   MEASURE  \0    Pharmaceuticals sales      I      BEL        Belgium  PH_SALES   1    Pharmaceuticals sales      I      BEL        Belgium  PH_SALES   2    Pharmaceuticals sales      I      BEL        Belgium  PH_SALES   3    Pharmaceuticals sales      I      BEL        Belgium  PH_SALES   4    Pharmaceuticals sales      I      BEL        Belgium  PH_SALES   ..                     ...    ...      ...            ...       ...   387  Pharmaceuticals sales      I      KOR          Korea  PH_SALES   388  Pharmaceuticals sales      I      CAN         Canada  PH_SALES   389  Pharmaceuticals sales      I      HUN        Hungary  PH_SALES   390  Pharmaceuticals sales      I      SWE         Sweden  PH_SALES   391  Pharmaceuticals sales      I      HRV        Croatia  PH_SALES                     Measure UNIT_MEASURE                       Unit of measure  \0    Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   1    Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   2    Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   3    Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   4    Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   ..                    ...          ...                                   ...   387  Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   388  Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   389  Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   390  Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted   391  Pharmaceutical sales   USD_PPP_PS  US dollars per person, PPP converted        ... OBS_STATUS  Observation status OBS_STATUS2 Observation status 2  \0    ...        NaN                 NaN         NaN                  NaN   1    ...        NaN                 NaN         NaN                  NaN   2    ...        NaN                 NaN         NaN                  NaN   3    ...        NaN                 NaN         NaN                  NaN   4    ...        NaN                 NaN         NaN                  NaN   ..   ...        ...                 ...         ...                  ...   387  ...        NaN                 NaN         NaN                  NaN   388  ...          D  Definition differs         NaN                  NaN   389  ...          D  Definition differs         NaN                  NaN   390  ...        NaN                 NaN         NaN                  NaN   391  ...        NaN                 NaN         NaN                  NaN        OBS_STATUS3  Observation status 3  UNIT_MULT  Unit multiplier DECIMALS  \0            NaN                   NaN          0            Units      NaN   1            NaN                   NaN          0            Units      NaN   2            NaN                   NaN          0            Units      NaN   3            NaN                   NaN          0            Units      NaN   4            NaN                   NaN          0            Units      NaN   ..           ...                   ...        ...              ...      ...   387          NaN                   NaN          0            Units      NaN   388          NaN                   NaN          0            Units      NaN   389          NaN                   NaN          0            Units      NaN   390          NaN                   NaN          0            Units      NaN   391          NaN                   NaN          0            Units      NaN       Decimals  0        NaN  1        NaN  2        NaN  3        NaN  4        NaN  ..       ...  387      NaN  388      NaN  389      NaN  390      NaN  391      NaN  [392 rows x 28 columns]

Load the data

URL: https://data-explorer.oecd.org/vis?lc=en&df[ds]=dsDisseminateFinalDMZ&df[id]=HEALTH_PHMC%40DF_PHMC_SALES&df[ag]=OECD.ELS.HD&dq=..USD_PPP_PS.._T&pd=2010%2C&to[TIME_PERIOD]=false

In [11]:
pharmsales.info()

<class 'pandas.core.frame.DataFrame'>RangeIndex: 392 entries, 0 to 391Data columns (total 28 columns): #   Column                Non-Null Count  Dtype  ---  ------                --------------  -----   0   STRUCTURE             392 non-null    object  1   STRUCTURE_ID          392 non-null    object  2   STRUCTURE_NAME        392 non-null    object  3   ACTION                392 non-null    object  4   REF_AREA              392 non-null    object  5   Reference area        392 non-null    object  6   MEASURE               392 non-null    object  7   Measure               392 non-null    object  8   UNIT_MEASURE          392 non-null    object  9   Unit of measure       392 non-null    object  10  MARKET_TYPE           392 non-null    object  11  Market type           392 non-null    object  12  PHARMACEUTICAL        392 non-null    object  13  Pharmaceutical        392 non-null    object  14  TIME_PERIOD           392 non-null    int64   15  Time period           0 non-null      float64 16  OBS_VALUE             392 non-null    float64 17  Observation value     0 non-null      float64 18  OBS_STATUS            195 non-null    object  19  Observation status    195 non-null    object  20  OBS_STATUS2           13 non-null     object  21  Observation status 2  13 non-null     object  22  OBS_STATUS3           1 non-null      object  23  Observation status 3  1 non-null      object  24  UNIT_MULT             392 non-null    int64   25  Unit multiplier       392 non-null    object  26  DECIMALS              0 non-null      float64 27  Decimals              0 non-null      float64dtypes: float64(5), int64(2), object(21)memory usage: 85.9+ KB

Looking to see which columns are recorded as strings or floats

In [12]:
cancer_data= cancercare[['REF_AREA', 'TIME_PERIOD', 'OBS_VALUE']].rename(
    columns={'OBS_VALUE': 'Cancer_Rate'}
)
pharm_sales_data = pharmsales[['REF_AREA', 'TIME_PERIOD', 'OBS_VALUE']].rename(
    columns={'OBS_VALUE': 'Pharma_Sales'}
)

In the above kernal, I am extracting the columns of data that I need to make the chart

In [13]:
cancer_data_2014 = cancer_data[cancer_data['TIME_PERIOD'] == 2014]

# Check if pharma sales data exists
pharm_sales_data_2014 = pharm_sales_data[pharm_sales_data['TIME_PERIOD'] == 2014]

I only wanted to see the data for year 2014 and for Australia and Belgium

In [14]:
countries = ["BEL", "AUS"]

In [15]:
data_list = []
for country in countries:
    # Get cancer rate data for the country
    cancer_rate = cancer_data_2014[cancer_data_2014['REF_AREA'] == country]['Cancer_Rate'].mean()
    if pd.isna(cancer_rate):
        cancer_rate = 0  # Use placeholder if no data

    # Get pharmaceutical sales data for the country
    pharma_sales = pharm_sales_data_2014[pharm_sales_data_2014['REF_AREA'] == country]['Pharma_Sales'].mean()
    if pd.isna(pharma_sales):
        pharma_sales = 0  # Use placeholder if no data

    # Append data to the list
    data_list.append({'Country': country, 'Metric': 'Cancer Rate', 'Value': cancer_rate})
    data_list.append({'Country': country, 'Metric': 'Pharmaceutical Sales', 'Value': pharma_sales})

I made a list and a for loop for the cancer rates and pharm sales in Belgium and Australia

In [16]:
combined_data = pd.DataFrame(data_list)

Have to combined data frames into one in order to make the figure. It's much easier this way.

In [17]:
fig = px.bar(
    combined_data, 
    x='Country', 
    y='Value', 
    color='Metric', 
    barmode='group',
    title='Cancer Rate and Pharmaceutical Sales in Selected Countries (2014)', 
    labels={'Value': 'Value'}
)
fig.show()

I was hoping to see that if there was an increase in cancer rates that there would also be an increase in pharm sales, but I did not! I chose Belgium and Australia in the year 2014 because those were the countries with the most data that I could draw from (around 18 entries for both cancer rate and pharmaceutical sales for that year). Belgium and Australia have similar cancer rates for 2014 but differ drastically in their pharmaceutical sales indicating that there is not enough evidence to conclude there is a correlation between cancer rates and pharmacuetical sales for the year of 2014. Of course, I would have liked to have had data that showed each country over time to make a line plot but I could not find consistent data anywhere. Next time, I would also choose a bigger data set. The pharmaceutical sales data set being only 300 rows really impacted my ability to shape and portray the relationship that I wanted to orginally portray which was two lines - one for pharm sales and one for cancer rate for Belgium and Australia over a 10 year period.